[[mgr.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on="T"
run="plugin --sync hide-preview"
desc="Hide or show preview"

[[mgr.prepend_keymap]]
on="|"
run="plugin --sync max-preview"
desc="Maximize or restore preview"
